### ISSUE TITLE
Skip the spotlessCheck by default

### ISSUE THREAD

**Issue by agasvina** [diffplug/spotless#11]
Is it possible to run the ```spotlessCheck``` if we explicitly mention it?

At the moment, the command ```gradle build``` with this plugin automatically runs the ```spotlessCheck```. 
one of the work arounds  is to use the command ```gradle build -x spotlessCheck```.

Kindly advice

**Comment by nedtwigg** [comment]
Here's what happens when you do `gradlew build`:

![Java build task dependencies](https://docs.gradle.org/current/userguide/img/javaPluginTasks.png)
 *from the [Gradle manual, Figure 45.1. Java plugin - tasks](https://docs.gradle.org/current/userguide/java_plugin.html)*

Note that `build` depends on `check` and `test`.  The purpose of the `check` task is to aggregate all of the static code analysis results - FindBugs, CheckStyle, Spotless, etc - and fail the build if any of these fail.

If you just want to create your jar file, run `gradlew assemble`.  If you just want to run the tests, run `gradlew test`.  But `gradlew build` should run all static analysis (including `spotlessCheck`) according to the Gradle spec.
