### ISSUE TITLE
spotlessCheck not run as part of a gradle build

### ISSUE THREAD

**Issue by AlecStrong** [diffplug/spotless#1164]
- [x] summary of problem:
The `spotlessCheck` task is no longer run as part of a `build` execution. Confirmed by running `./gradlew build --dry-run`. The `spotlessCheck` task still exists and can be run manually.
- [x] gradle or maven version: 7.4.2
- [x] spotless version: 6.4.2
- [x] operating system and version: multiple (running on linux/mac/windows on CI)
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible: [repo](https://github.com/cashapp/sqldelight), with this main config in root build.gradle
```
spotless {
  kotlin {
    target "**/*.kt"
    targetExclude "**/gen/**/*.*", "**/generated/**/*.*", "sqldelight-compiler/integration-tests/src/test/kotlin/com/example/**/*.*", "sqldelight-compiler/src/test/migration-interface-fixtures/**/*.*"
    ktlint(deps.versions.ktlint.get()).userData(["indent_size": "2"])
    trimTrailingWhitespace()
    endWithNewline()
  }
}
```

**Comment by nedtwigg** [comment]
I think the chain is `build` -> `check` -> `spotlessCheck`.

The `build` and `check` tasks are setup by the `base` plugin, which Spotless used to apply itself, but we stopped because that caused some conflict with the Android plugin.

Are you sure that your project has a `build` or `check` task? You can get them by applying `base`.

**Comment by AlecStrong** [comment]
yea build and check are both still there (via running `./gradlew tasks`). I can confirm though that applying `base` fixes this problem and the spotless tasks are added to the task dependencies

**Comment by nedtwigg** [comment]
Based on https://github.com/cashapp/sqldelight/blob/master/build.gradle, I suspect that your root project actually does not have a `build` or `check` task (unless someone applies `base`), and `./gradlew tasks` is showing you the tasks of the subprojects, not the root project.

But this feels like Spotless should just always apply `base`. That's what we did until [December 2021 in `6.0.3`](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#603---2021-12-06) when we stopped (#1014) mostly just because some Android template manually created a `clean` task which interfered with any plugin that relied on the conventions in `base`, but Google has since fixed that, so I think we probably made a mistake by adapting to their bug.

You can fix this by applying `base`, but I'm inclined to make Spotless eagerly apply `base` itself in a future release unless someone talks me out of it before then.

**Comment by jbduncan** [comment]
I'm working on an Android project that still uses the `clean` task generated by the old version of the Android template.

So the only thing I'd encourage is to add some instructions to the release notes on how to adapt any existing, custom `clean` tasks.

It's probably just a matter of changing any such tasks to something like:

```kotlin
tasks.named<Delete>("clean") {
    . . .
}
```

...as opposed to `tasks.registering`, which is what we're using.

We're using the Gradle Kotlin DSL in our project, so I'd need to dive into our VCS history or crack open an old version of Android Studio to remind myself what the Groovy syntax is.

(Having said all this, it's worth noting that we don't use Spotless... yet? 😁)

**Comment by AlecStrong** [comment]
:+1: sounds good, thanks. I'll apply base for now and remove it in a future spotless release

**Comment by nedtwigg** [comment]
Base is now applied eagerly starting with `plugin-gradle 6.5.0`.

**Comment by AlecStrong** [comment]
confirmed fixed, thanks :+1:
