### ISSUE TITLE
CRLF will be converted to LF when submitting documents

### ISSUE THREAD

**Issue by longtai-cn** [diffplug/spotless#1171]
Hello, I encountered the problem of transferring CRLF to LF when using spotless. The details are as follows

- [ ] summary of problem
CRLF will be converted to LF when submitting documents.

![image](https://user-images.githubusercontent.com/77398366/163899941-462e63ec-26bf-4946-a770-50f1c7114e42.png)

- [ ] gradle or maven version
apache-maven-3.5.4

- [ ] spotless version
2.21.0

- [ ] operating system and version
![image](https://user-images.githubusercontent.com/77398366/163900296-79a4f7fe-8417-4505-b93a-55397953ff5b.png)

- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```xml
<plugin>
    <groupId>com.diffplug.spotless</groupId>
    <artifactId>spotless-maven-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <java>
            <includes>
                <include>src/test/java/**/*.java</include>
            </includes>
            <eclipse>
                <file>${session.executionRootDirectory}/dev-support/shardingsphere_eclipse_formatter.xml
                </file>
            </eclipse>
            <licenseHeader>
                <file>${session.executionRootDirectory}/dev-support/license-header</file>
            </licenseHeader>
        </java>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>apply</goal>
            </goals>
            <phase>compile</phase>
        </execution>
    </executions>
</plugin>
```

- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`
ignore

**Comment by nedtwigg** [comment]
I believe this is the expected behavior. https://github.com/diffplug/spotless/tree/main/plugin-maven#line-endings-and-encodings-invisible-stuff

If you want all files to be `\r\n` I would add a `.gitattributes` file with `* text eol=crlf`. If it's just certain files then I would adjust the wildcard appropriately.

Another option is to set `<lineEndings>WINDOWS</lineEndings>` but you will be fighting against git if you do that, which I don't recommend.

Perhaps you wish that Spotless detected the line endings per-file, and just kept them as-is? We don't support that right now, but I'd be happy merge that as a new line endings mode (#1172).
