### ISSUE TITLE
Use SpotlessApply in build grudlew

### ISSUE THREAD

**Issue by amarsova** [diffplug/spotless#1222]
Hi everyone I use 
```
gradle
spotless version 3.26.1
operating system : Mac 
```

My build.grudge.kts  like :
```
plugins {
   id("com.diffplug.gradle.spotless") version "3.26.1"
}
--------------------------------------------------------
spotless {
    scala {
        scalafmt("2.7.0").configFile(rootProject.file(".scalafmt.conf"))
    }

}
```

if I want to check the Spotless I need to run ./grudlew spotlessCheck and then spotlessApply to fix the code 
Is there any possibility to run the spotlessApply every time  when we Build the project

**Comment by nedtwigg** [comment]
You can do `build.dependsOn(spotlessApply)` or something like that. I strongly recommend against this, for this reason:

- you commit code which badly formatted
- you push to CI
- CI runs spotlessApply, which changes the code, then spotlessCheck and all tests pass
- your code history is now full of code which is not correctly formatted, but passed CI anyway

**Comment by Pankraz76** [comment]
### **Stop Wasting Time on Formatting – Automate It Properly**  

This seems like an overly theoretical debate, ignoring Gradle’s full potential. The solution is simple, just like proposed in:

- https://github.com/diffplug/spotless/pull/2528

1. **Fix automatically in local dev** (so nobody wastes time manually adjusting whitespace).  
2. **Only check in CI** (to catch inconsistencies).  

That’s it. No back-and-forth, no manual fixes—just **eliminating the pointless formatting churn** that, as you mentioned yourself, this project is all about.

- https://github.com/diffplug/spotless/pull/2524#issuecomment-3002059471 

Tools like Maven, Quarkus and PMD already do this. Why? Because **engineers should focus on real work, not whitespace.**  

My build failed 5 times so did the CI, wasting your money.

Let’s **actually solve the problem** instead of overcomplicating it.

**Comment by Pankraz76** [comment]
The scenario you're describing is designed to fail. Just fix it so it works. We already check formatting in CI. Just apply auto-fix formatting locally on the developer's machine, only.

So `CI` will check, `dev` will fix. No interference.

What's the issue with letting small whitespace issues block contributions?

This tools is supposed to make formatting easy. Why not follow the practices of bigger, well-maintained projects with large dev communities?
