### ISSUE TITLE
Provide an option for including only files that are managed by git

### ISSUE THREAD

**Issue by ndimiduk** [diffplug/spotless#1232]
This is a feature request for the maven plugin. Because there's already some nice git integration by way of the ratchet-from feature, I hope this isn't too much of a stretch. Rather than explicitly specifying a list of ignore patters, I would like to configure spotless to only look at files that are managed by git in the current branch. It should also consider staged files that are newly added but not committed.

Thanks!

**Comment by nedtwigg** [comment]
Interesting! I like the idea of "just use git to figure out what's included", but unfortunately it's not that simple because you still need to filter based on e.g. `*.java` or maybe (include `*.html` but exclude `*.template.html`).

I think the trickiest part of this is actually the documentation. I'm going to close this as "won't implement", but if you (or anyone else) opens a PR to the docs which provides a good clear interface, then I'll reopen and we can figure out how to implement it.
