### ISSUE TITLE
Task spotlessJava not triggering when only formatting code

### ISSUE THREAD

**Issue by carcaret** [diffplug/spotless#127]
I'm not sure if this has been discussed before or it's intended behavior.

I've just added the plugin to an existing project for code formatting. When running a new build, I've noticed that this configuration is not triggering the `spotlessJava` task, so the build is successful even though the code is badly formatted:
```
spotless {
    java {
        eclipseFormatFile 'format/eclipse-java-google-style.xml'
    }
}
```
However, adding for instance a call to `removeUnusedImports()` before seems to trigger `spotlessJava` task successfully and the build therefore fails as intended since the code is not formatted:
```
spotless {
    java {
        removeUnusedImports()
        eclipseFormatFile 'format/eclipse-java-google-style.xml'
    }
}
```
Shouldn't the first configuration trigger the `spotlessJava` task and make the build fail?

I'm using Gradle v3.4.1 and Java 1.8.0_131-b11

**Comment by carcaret** [comment]
Nevermind, looks like `eclipseFormatFile` is deprecated. By using the syntax `eclipse().configFile 'format/eclipse-java-google-style.xml'` runs fine.

**Comment by jbduncan** [comment]
Hi @carcaret, glad to see that you managed to resolve your problem.

On a kind of related note, I highly encourage you to use the `googleJavaFormat()` option instead of `eclipse().configFile 'format/eclipse-java-google-style.xml'`, as the Eclipse formatting file for Google Java Style is merely an _approximation_; `googleJavaFormat()` uses https://github.com/google/google-java-format in the background, which is a custom formatter made by Google themselves for conforming to the conformable parts of Google Java Style as closely as possible.

**Comment by nedtwigg** [comment]
Any chance we can get a link to the project you're using it on?

**Comment by fvgh** [comment]
@carcaret : I am responsible for the code change #109, declaring `eclipseFormatFile` deprecated.
Since I just made a similar change for another method, I just want to ensure that I haven't missed something. I would appreciate if you could help to clarify the issue.
I tried the following set-up:

```
buildscript {
    repositories { mavenCentral() }
    dependencies {  classpath 'com.diffplug.spotless:spotless-plugin-gradle:3.4.1' }
}
apply plugin: 'com.diffplug.gradle.spotless'
apply plugin: 'java'
spotless {
    java { eclipseFormatFile 'format/eclipse-java-google-style.xml' }
}
```

I got:
```
.../testbed_spotless$ gradle build
'eclipseFormatFile [version] <file>' is deprecated.
Use 'eclipse([version]).configFile(<file>)' instead.
For details see https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:spotlessJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessJava'.
> The following files had format violations:
      src/main/java/testbed_spotless/test.java
          @@ -1,3 +1,4 @@
           package·testbed_spotless;
           
          -class·Test·{};
          +class·Test·{
          +};
  Run 'gradlew spotlessApply' to fix these violations.
```

I am using a slightly different gradle and java version, but that should not have cause the issue.

Anything else you can think of, which is different  in your set-up?
Thanks in advance for your time and effort!

**Comment by carcaret** [comment]
I´ve tried to reproduce the issue at home in a simple project with no success. 
On the other hand, I might be able to share the original `build.gradle` file with you. Let me get back to you on Monday.

**Comment by fvgh** [comment]
Thanks a lot.
On 29/07/2017, 19:17 carcaret <notifications@github.com> wrote:
I´ve tried to reproduce the issue at home in a simple project with no success.
On the other hand, I might be able to share the original build.gradle file with you. Let me get back to you on Monday.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/diffplug/spotless","title":"diffplug/spotless","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/diffplug/spotless"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carcaret in #127: I´ve tried to reproduce the issue at home in a simple project with no success. \r\nOn the other hand, I might be able to share the original `build.gradle` file with you. Let me get back to you on Monday."}],"action":{"name":"View Issue","url":"https://github.com/diffplug/spotless/issues/127#issuecomment-318845224"}}}

**Comment by carcaret** [comment]
I've been trying with no success to reproduce the error using the original `build.gradle` in a different project. Actually, copying exactly the same project to a new folder and launching `gradle clean build` is working fine regardless the order. 
I guess the issue had something to do with my file system and something maybe corrupted or in an unstable state. Guess you can close the issue, sorry for the trouble.

**Comment by fvgh** [comment]
No worries. There are many different setups possible with Gradle, so I can't test them all. Hence I depend on user feedback. Thanks for the clarification.

**Comment by nedtwigg** [comment]
We do some [tricky stuff to make up-to-date checking work](https://github.com/diffplug/spotless/blob/0b5fe2dbcf6234df62d9b7e91339b5b689ad0c3c/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPlugin.java#L70-L99).  `spotlessCheck` and `spotlessApply` are zero-work marker tasks that configure `spotless`, which does the actual work.  It mighta seemed like the task you asked for wasn't running, when it actually was.  Regardless, all good :)  Reopen if you're able to reproduce.
