### ISSUE TITLE
Support removing of license header at other locations

### ISSUE THREAD

**Issue by kwin** [diffplug/spotless#1419]
By default license headers in Java are injected before the `package` delimiter. In order to clean up old license headers at other positions (after the `package` statement) there should be an optional cleanup of license headers at other positions in a file with the `LicenseHeaderStep`.

**Comment by nedtwigg** [comment]
It's easy to [add custom steps](https://github.com/diffplug/spotless/tree/main/plugin-gradle#custom-steps).

I'm happy to take a PR for something like this - the hard part is always the documentation. I would write the docs that explain how the step is able to detect whether something is a license or a comment, and what it's supposed to do, and how you configure it.

If those docs end up super complicated, then probably it's not a good fit for the entire community (but it could be if the complexity is optional-only). And maybe the easiest thing is to make a custom step that happens to work for your codebase while you transition it, and then you can remove it and rely on community-maintained stuff from there.

**Comment by slawekjaranowski** [comment]
IMHO should not be closed ... issue still exist. 

You mention custom step for Gradle build ... but what with Maven build

**Comment by nedtwigg** [comment]
> what with Maven build

For maven there are a few [generic commands](https://github.com/diffplug/spotless/tree/main/plugin-maven#generic-steps) that can work.

- jsr223
- nativeCmd
- replaceRegex

> should not be closed ... issue still exist.

When it comes to feature requests, I keep them open only if I think they might get added someday. Things get added because:

- they are easy (a new formatter)
-  OR
- they are hard but really useful (git ratchet)

My guess is that this feature is hard and not useful for very many people, and even for those people who need it I don't think they need it for long enough to be worth maintaining on an ongoing basis.  But I'm wrong all the time, so I added in the closing how to move forward if someone wants to.

I try to never block someone from moving forward with something where Spotless could help them, but I also try to be honest about where I think time investments are likely to be fruitful. If I had this problem, I would hack something together that works one time to move license headers to the standard location, copy-paste it into this issue so I could find it again later if I needed it, and move on. But it could become a big project if someone wants such a project, and as I said above

> I'm happy to take a PR for something like this - the hard part is always the documentation. I would write the docs that explain how the step is able to detect whether something is a license or a comment, and what it's supposed to do, and how you configure it.

**Comment by slawekjaranowski** [comment]
@nedtwigg Thanks for explanation. Indeed this issue is needed only during migration ... once time. 

So I agree that probably will be not implemented.
