### ISSUE TITLE
Upgrade to Eclipse 4.5.1+ regarding bug fixes in formatter

### ISSUE THREAD

**Issue by sbrannen** [diffplug/spotless#15]
## Overview

As discussed in the [JUnit 5 repository](https://github.com/junit-team/junit5/pull/179), the Eclipse Java formatter used by Spotless 1.3.2 is hard coded to version `R-4.5-201506032000` (see `build.gradle` for Spotless), and this version contains a bug regarding whitespace after `[]` in annotation attribute declarations.

This bug has been fixed in [Eclipse 4.5.1 and 4.6](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472962#c5).

However, since Spotless embeds the Eclipse JARs, it is (AFAIK) not possible to perform an upgrade to the Eclipse version used by Spotless.

## Deliverables

- [ ] Either release a version of Spotless that embeds Eclipse 4.5.1+
- [ ] Or release a version of Spotless that makes it possible to upgrade the version of Eclipse used by Spotless via standard dependency management within a Gradle build
- [ ] Or release a version of Spotless that provides both of the aforementioned improvements

**Comment by nedtwigg** [comment]
I've already upgraded to 4.5.2, and I'll publish it later today after finishing a little more testing.

Unfortunately, Eclipse is only distributed using p2 repositories, not maven.  In order to download from p2 repositories, I have to trick Gradle into thinking a p2 repository is an ivy repository, which only works if I manually enter the version numbers from the p2 metadata.  So Spotless will have to hardcode the eclipse dependency until Gradle supports p2, and there's no sign of that changing anytime soon.

**Comment by nedtwigg** [comment]
Just published [Spotless 1.3.3](https://github.com/diffplug/spotless/blob/master/CHANGES.md#version-133---march-10th-2016-jcenter) which uses Eclipse 4.5.2.

**Comment by sbrannen** [comment]
Wow... that was crazy fast.

Amazing support! :+1: 

And... I've already upgraded JUnit 5 accordingly: https://github.com/junit-team/junit5/commit/28637e6b6eeae797291c8f31902b09aa0fca594a

Thanks!

**Comment by sbrannen** [comment]
And yeah, that's a pity about p2 and Gradle.

So we just have to live with it for the time being. Thanks for the explanation of the root cause.

**Comment by nedtwigg** [comment]
Coincidentally, I was already working on it at EclipseCon because of #14 when you sent your issue.  Lucky break :+1:
