### ISSUE TITLE
Update version of Gradle built with

### ISSUE THREAD

**Issue by JLLeitschuh** [diffplug/spotless#161]
You can update the version of gradle that is used to build this project but still run the tests with the tooling API to test version `2.6`.
This has been deprecated but will still be supported in `4.3`
https://docs.gradle.org/current/release-notes.html#deprecations

Is there a reason why this project is still built with `2.6`? Can we upgrade? Will we see a benefit (checking forward compatibility would be a good use case)?

**Comment by nedtwigg** [comment]
It's built with [`2.14.1`](https://github.com/diffplug/spotless/blob/e3556ddbd1dc2d7b8041101d62efd2bcddbafd5d/gradle/wrapper/gradle-wrapper.properties#L6), not `2.6`.  Probably the build will be faster with a newer version, but we'll have to rely on testing to make sure it still works with the older versions, rather than compile-time checks.

I'd like to maintain compat with `2.14+`.  I've got some projects stuck on `2.14` indefinitely [because in `3.x +` any change to `buildSrc` causes a full rebuild](https://discuss.gradle.org/t/workaround-for-any-change-to-buildsrc-making-all-tasks-become-out-of-date/20592).

I'd be happy to merge an update to `4.3` that includes testing against `2.14`, but I don't care about this enough to do it.
