### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [diffplug/spotless#1648]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@oiiwroo) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by nedtwigg** [comment]
Thanks for letting us know! I just added

https://github.com/diffplug/spotless/blob/main/SECURITY.md

**Comment by nedtwigg** [comment]
For anyone who is interested

- the bug being reported has nothing to do with the Spotless project
- DiffPlug, our sponsoring company, has a commercial product which includes a license manager, and this license manager had an XSS vulnerability
- We very much appreciate that this was found and reported, it is now fixed, we went through our logs to confirm that it had not been exploited
- But that doesn't matter at all to Spotless users, because again, the vulnerability wasn't in the Spotless project

**Comment by oiiwroo** [comment]
Hi @nedtwigg, I haven't received the bounties yet, have any problems with my report

**Comment by nedtwigg** [comment]
The problem is that you were reporting vulnerabilities through some kind of foundation (I can't find the link) that finds bugs in open source software. DiffPlug's license manager is not open source. You found a bug in the license manager, and reported the bug against Spotless.

I documented this above, and also at the open source foundation. I don't have your contact information, but you do have mine (it's also in my GitHub profile). I'm not going to issue an incorrect CVE against Spotless, and to pay you through the portal you issued me requires that I do so.

I'm happy to discuss further, but it has nothing to do with Spotless, and I don't want to generate more noise on this topic in the Spotless issue tracker.
