### ISSUE TITLE
Add support for "Number Of Imports Needed Imports for .*"

### ISSUE THREAD

**Issue by im-bob-loucans** [diffplug/spotless#17]
More of a feature request if it does not already exist in the tool.

Is it possible to apply the "Number Of Imports Needed Imports for .*" preference when organizing imports?

**Comment by nedtwigg** [comment]
It's definitely possible!  It's not a priority for me, but I'd be happy to merge a PR, and to help along the way.

For code formatting, we use the actual jars from Eclipse.  For import sorting, we have a knockoff that can read Eclipse's import files, but it doesn't support all of their functionality.

[ImportSorterStep](https://github.com/diffplug/spotless/blob/7ef7c50aa15d7396d0aa47eaef7e3c0105ba7680/src/main/java/com/diffplug/gradle/spotless/java/ImportSorterStep.java) is what reads the user's input, and [ImportSorterImpl](https://github.com/diffplug/spotless/blob/7ef7c50aa15d7396d0aa47eaef7e3c0105ba7680/src/main/java/com/diffplug/gradle/spotless/java/ImportSorterImpl.java) is what does the actual import sorting.  The impl part is copied from [https://github.com/krasa/EclipseCodeFormatter](https://github.com/krasa/EclipseCodeFormatter/tree/bc9a82c605a82560c75e312e33d57b62cecd2f2f/src/java/krasa/formatter/plugin).  It looks like they've made a lot of progress since we last incorporated their work.

If you (or anyone else) is interested in digging into this, I'd be happy to offer help here or in the gitter channel.

**Comment by nedtwigg** [comment]
I just dug into this a little, and krasa/EclipseCodeFormatter hasn't implemented this.  If we wanted to use the Eclipse implementation, the key code is this: [`org.eclipse.jdt.core.dom.rewrite.ImportRewrite.java`](https://github.com/eclipse/eclipse.jdt.core/blob/b51cc5d8fad9e9863182caa1bdcc31e7c01d0d67/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/rewrite/ImportRewrite.java), and here's an example of it in use: [`ImportRewriteTest`](https://github.com/eclipse/eclipse.jdt.core/blob/947633cd3e536904a3c62f9fa98185b52f85fb30/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/rewrite/describing/ImportRewriteTest.java).

**Comment by im-bob-loucans** [comment]
Well I finally got to fork the project.   See what I can do over the next couple of weeks

**Comment by nedtwigg** [comment]
Great, thanks!  Just as a heads-up, I'll be updating Spotless to Eclipse Neon and Gradle 2.14 around late June, as well as [adding support for .gitattributes](https://github.com/diffplug/spotless/issues/23).  This won't affect any Spotless API's, and I highly doubt that the Eclipse Neon API will be much different than the Mars API, so we shouldn't have any conflicts.

**Comment by sbrannen** [comment]
It's not super high on our priority list, but.... the JUnit 5 team would certainly appreciate seeing this support implemented in Spotless. 😉

**Comment by nedtwigg** [comment]
One year without progress.  Also, `googleJavaFormat()` is gaining popularity, and it bans wildcard imports.  Future contributors are free to reopen if any progress is made.

**Comment by sbrannen** [comment]
😞

**Comment by DJViking** [comment]
Has there been any improvements to enforce the googleJavaFormat of banning wildcard imports?
The Eclipse formater I am using with Spotless (which is derived from the Google standard) does remove the wildcard imports in the IDE, but spotless does nothing about it.

    java {
        importOrderFile 'config/spotless/my-eclipse.importorder'
        eclipse().configFile 'config/spotless/my-eclipse-format.xml'

        trimTrailingWhitespace()
        removeUnusedImports()
    }

**Comment by nedtwigg** [comment]
There isn't and there probably won't be.  For example:

```java
import pkgA.*;
import pkgB.*;

public class Test {
  AmIFromAorB field;
}
```

When you organize imports in eclipse, the IDE knows whether `AmIFromAorB` came from A or B, so it can dereference it properly.  But spotless's model is just `Function<String, String>`, so it doesn't know the whole build path, and it would be very difficult to change this.

**Comment by DJViking** [comment]
I don't mean spotless should change it, but allow to fail if wildcard imports are used.

    failIfWildcardImports()

**Comment by nedtwigg** [comment]
Ahh.  I am not aware of anyone currently working on the issue, but the issue you want to watch is probably #167

**Comment by rnett** [comment]
Google Java Format doesn't handle this apparently (google/google-java-format#113), so it would be nice to have here.  Doesn't seem easy though.
