### ISSUE TITLE
all .eslintrc.json rules are not getting evaluated for typescript project

### ISSUE THREAD

**Issue by ajaysuwalka** [diffplug/spotless#1742]
- [ ] summary of problem - **All .eslintrc.json rules are not getting evaluated, There're different results when I run `npm run lint` vs `./gradlew spotlessCheck` and I want to know what's preventing this. I want to specifically emphasise on the rule `@typescript-eslint/no-floating-promises`**
- [ ] gradle version - **8.1.1**
- [ ] spotless version - **6.14.1**
- [ ] operating system and version - **MacOS 13.3.1 (a) (22E772610a)**
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible - **[Demo project](https://github.com/ajaysuwalka/eslint-spotless-issue)**
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace` - **Easily reproducible using the commands mentioned in `#1`**

**Comment by simschla** [comment]
Thanks for raising the issue @ajaysuwalka. I hope I can clarify some things.

You need to understand that spotless - as of now - is not a linter, but a formatter. So running `gradlew spotlessCheck` is not the same as running `npm run lint`. Spotless uses eslint with the `--fix` parameter to fix eslint issues, that can automatically be fixed by eslint. That being said, it is clear why the `@typescript-eslint/no-floating-promises` rule is not respected in `spotlessCheck`: it is not a rule that can be automatically fixed by eslint, so it does not show up in `spotlessCheck`.

If you're interested in seeing spotless being able to act as a linter, I suggest you follow the corresponding issue #1097

**Comment by simschla** [comment]
Closing as answered for now. Please don't hesitate to reopen if I missed anything.
