### ISSUE TITLE
LicenseHeaderFile does nothing

### ISSUE THREAD

**Issue by bill-safehealth** [diffplug/spotless#1796]
Trying to apply a license header to all java files in an Intellij gradle project. 

   spotless {
        java {
            importOrder()
            removeUnusedImports()
            cleanthat()          // has its own section below
            palantirJavaFormat()
            formatAnnotations()  // fixes formatting of type annotations, see below
            licenseHeaderFile('$PROJECT_DIR$/LICENSE')
        }
    }

Running spotlesscheck produces - 

* What went wrong:
A problem occurred configuring project ':opencdx-proto'.
> Could not create task ':opencdx-proto:spotlessJava'.
   > java.nio.file.NoSuchFileException: /Users/bihaber/opencdx/gRPCTemplate/opencdx-proto/$PROJECT_DIR$/LICENSE

opencdx is one of the modules in the project which leads me to believe that muli modules are not supported or my configuration is wrong.

**Comment by jbduncan** [comment]
@bill-safehealth Welcome! I wonder if your problem is that `$PROJECT_DIR$` is supposed to be `$projectDir` (or even just `projectDir` if you use string concatenation rather than string interpolation). What happens if you try that?

(I think this because your stack trace shows that `$PROJECT_DIR$` is not being replaced with your actual Gradle project directory, so it just looks like a silly Gradle mistake to me. 🙂)

**Comment by bill-safehealth** [comment]
Thanks for your response.  The path was part of the issue but the real problem was that I didn't realize I had to setup spotless in the gradle.build file for each module. I expected the gradle.build in the root directory would apply to the other modules as well. Please confirm that this is the case as it affects the spotless actions in those modules.

**Comment by bill-safehealth** [comment]
I was able to get past my issue.  It might be helpful if your documentation included any tips for multi module setup in IntelliJ
