### ISSUE TITLE
Update default version of ktlint to 0.14.0

### ISSUE THREAD

**Issue by magneticflux-** [diffplug/spotless#181]
The current default (`0.6.1`) is far behind the current version of ktlint (`0.14.0`) and I ran into some bugs that had already been fixed in the current version: shyiko/ktlint/issues/133

**Comment by nedtwigg** [comment]
Good call, this'll make it into the next release.  In the meantime, you can pass a version to Spotless:

```gradle
spotless {
  kotlin {
    ktlint('0.14.0')
    ...
```

**Comment by magneticflux-** [comment]
Just ran into this again 🤣. Maybe having a moving target (`0.+`) would be better as a default and just let people lock to an older version if necessary.

**Comment by nedtwigg** [comment]
I think reproducible builds are really valuable, and Spotless' default values will always be 100% reproducible out of the box. If you want to trade away long-term reproducibility for always-the-latest,  then you can opt-in to that by setting your scripts to `ktlint('0.+')`. That would work for most Spotless formatters, but not for ktlint because of this line, happy to take a PR to solve this:

https://github.com/diffplug/spotless/blob/a98aea0eac6789868f477a924e71172511074de8/lib/src/main/java/com/diffplug/spotless/kotlin/KtLintStep.java#L100

I think the important part of Spotless is the connective tissue that allows users to compose any formatter with any other, and get buildcache, git ratchet, etc for free. Spotless promises to keep all of its existing features working at a high level of quality.

I don't think it's important for Spotless to ship a new version with an updated default every time that any of our dozen+ supported formatters ships a new version. Spotless-the-project makes no promise that it will proactively adopt the latest version of everything it has ever supported. Always happy to take PRs to update these defaults, but I don't consider it a defect if Spotless' defaults lag behind. If anyone disagrees with that lazy policy, all they have to do is submit the updated defaults as PRs, and I'll quicky merge and release them.
