### ISSUE TITLE
C/C++ support

### ISSUE THREAD

**Issue by fvgh** [diffplug/spotless#232]
I would like to provide C/C++ formatting support.
The following features shall be initially provided:

*  C/C++ formatter based on CDT (see #231)
*  Include order changes based on existing code for `ImportOrderStep`
*  Extension for Gradle/Maven whereas Maven will use default file name extensions and Gradle probably the native-specs (have to do some reading first...)

**Comment by fvgh** [comment]
I provided an [example use case](https://github.com/google/samba-documents-provider/compare/master...fvgh:spotless_support). Feedback is welcome.

**Comment by fvgh** [comment]
Formatting accomplished with #295.
Sorting of `include` statements still to be supported. Hence this issue remains open.

**Comment by fvgh** [comment]
The usage of IncludeOrganizer as it is provided by CDT is not an option.

- The amount of dependencies on other Eclipse components is quite high.
- Only a very small set of options is supported without pre-knowledge of the project setup (knowledge which headers belong to other libraries). Unfortunately even the header substitution is not applied.
- The results differ for the same configuration depending whether it is run with a project or without. This cannot be easily worked-around.

All in all it seems a better idea to implement an own organizer similar to the Spotless Java Import sorter.

**Comment by nedtwigg** [comment]
I try to keep the issues in-sync with our releases, but I missed this one!  We have had C/C++ support since:

- [plugin-maven 1.15.0](https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md#1150---2018-09-23) 2018-09-23
- [plugin-gradle 3.15.0](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md#3150---2018-09-23) 2018-09-23

It seems like a missing piece is an include organizer.  One option is to build one from scratch, another would be to use clang-format (#475), and follow it up with `eclipseCdt()`.  Regardless, even without include organizing, it's tremendously valuable to have Eclipse CDT's autoformatter included, thanks so much @fvgh!  I'm going to close this as "long-ago implemented", and if you have a specific unmet need, feel free to open a new issue.

**Comment by nedtwigg** [comment]
As of `5.2.0` we also support `clang-format`.
