### ISSUE TITLE
lineEndings cannot be set

### ISSUE THREAD

**Issue by aram535** [diffplug/spotless#24]
We have a multi-platform developer environment and switching code between Windows, Mac and Linux is causing all sorts of line ending problem.

I tried adding: 

`lineEndings = PLATFORM_NATIVE `

`lineEndings = UNIX `

in the applies spotless  { } but it thrown an exception:

`Could not find property 'PLATFORM_NATIVE' on com.diffplug.gradle.spotless.SpotlessExtension_Decorated@1d012c85.`

Is there an import missing?

**Comment by nedtwigg** [comment]
Spotless uses [PLATFORM_NATIVE](https://github.com/diffplug/spotless/blob/918a631c1a738964d870ee0ad7d157f4c00b7a9f/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java#L36-L45) by default, so if you don't set anything, it will use PLATFORM_NATIVE already.


If you're having line ending problems, I'm guessing you wanna setup [.gitattributes](https://git-scm.com/docs/gitattributes) so that all the line endings get converted to the same type when they are committed.

**Comment by aram535** [comment]
No I actually want to use UNIX, but you cannot set the lineEndings to any value at all as the documentation and examples suggest.

**Comment by nedtwigg** [comment]
Ah, sorry.  The example is indeed wrong.  Thanks for pointing this out!!  This will work:

`lineEndings 'UNIX'`
