### ISSUE TITLE
How to disable formatting for snippet? Java/Maven

### ISSUE THREAD

**Issue by mattcopas** [diffplug/spotless#275]
How do I turn off formatting for a certain bit of code?

I am trying to disable it for a method chain.

I've tried using // @formatter syntax
e.g.

```
public void foo() {
  // @formatter:off
  here()
    .dont().format()
  .the()
       .code();
  // @formatter:off
  // format as normal from here...
}
```

but this approach doesn't seem to work.

Is there a way to do this in spotless?

Thanks

**Comment by jbduncan** [comment]
Hi @mattcopas, welcome to Spotless!

What formatter from Spotless are you using? Does your setup look more like this:

```gradle
spotless {
  java {
    eclipse().configFile(...)
  }
}
```

or more like this:

```gradle
spotless {
  java {
    googleJavaFormat(...)
  }
}
```

or more like this?

```gradle
spotless {
  java {
    custom(...)
  }
}
```

If you're using `eclipse()`, then using `// @formatter:off` and then `// @formatter:on` _should_ work fine.

If you're using `googleJavaFormat()`, then sadly google-java-format explicitly _doesn't_ support those tags, since it's meant to be a a very simple solution where everyone can agree on a common style without nitpicking (https://github.com/google/google-java-format/issues/137).

If you're using a custom step or something else, I'd love it if you could provide us with more context e.g. an [MVCE](https://stackoverflow.com/help/mcve) so we can understand better what you're trying to achieve. :)

**Comment by jbduncan** [comment]
Oh, I should have asked first: are you using the Gradle plugin or the Maven plugin?

**Comment by mattcopas** [comment]
@jbduncan Thanks for the quick response. We're using the google format, so it actually looks like this isn't a spotless issue but a google one (thank you for the link).

Closing as out of scope.

**Comment by jbduncan** [comment]
@mattcopas You're very welcome!

I don't know if this will help, but with Spotless you can _exclude_ certain files from being formatted, so if you have Java files that contain a lot of DSL-like code or unusual method chaining, you could exclude them from being formatted by google-java-format and manually format and maintain them yourself.

Something like the following (untested, and may only work with Gradle's Kotlin DSL!):

```gradle
spotless {
  java {
    target(fileTree("src/**/*.java") {
        exclude(
            "**/com/company/package/FirstFileWeDoNotWantToFormat.java",
            "**/com/company/package/SecondFileWeDoNotWantToFormat.java")
    })
  }
}
```

**Comment by nedtwigg** [comment]
Just an update that since `plugin-gradle 5.5.0` and `plugin-maven 2.3.0`, it is now possible to use any formatter, in any language, and exclude specific snippets [with `spotless:off` tags](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson).

**Comment by hanoch** [comment]
How do I "enable toggleOffOn()" from the maven plugin?

**Comment by hanoch** [comment]
BTW - is there a similar syntax to temporarily override a *.prefs property, such as `lineWidth=150`, in a specific file segment?

**Comment by nedtwigg** [comment]
#817 is the closest we've got.
