### ISSUE TITLE
Standardize multiple consecutive newlines check

### ISSUE THREAD

**Issue by mkordas** [diffplug/spotless#307]
It is common to prohibit multiple consecutive newlines in all types of files as generally it doesn't make sense to have more than one empty line between sections of code.

Right now I can do
```
replaceRegex 'Remove consecutive newlines', '\n\n\n+', '\n\n'
```
but it uses regex and it is not efficient. 

I propose to create dedicated check, e.g. `removeConsecutiveNewlines()` and implement it in more optimal way (without regex).

**Comment by nedtwigg** [comment]
We actually implement `trimTrailingWhitespace` with a regex step.  It's almost definitely not worth taking on the complexity for a possible (but not guaranteed) performance gain, but it might be worth adding an easy-to-spell shortcut for this fairly common use case.

https://github.com/diffplug/spotless/blob/3c132d1f2322b77bce4e8cf395ad18ee35d2cbcd/lib/src/main/java/com/diffplug/spotless/generic/TrimTrailingWhitespaceStep.java#L24-L26

On https://github.com/diffplug/spotless/blob/master/README.md, we keep an index of every single step that we support.  The smaller that is, the less we have to maintain, and the less users have to learn.  Mostly, we should restrict ourselves only to *irreplaceable* steps, and avoid lots of convenience steps.

`IndentStep` turned out to be a mistake - search the issues and users are frequently confused about what the proper behavior should actually be, and it's natural with `IndentStep` to want things that aren't actually possible.

`trimTrailingWhitespace` is also a little confusing.  Does it guarantee that files will always end with newline?  No.  Should it?  Some would say yes, some no, so maybe we should add `alwaysEndWithEmptyLine`.  Should this rule turn *empty* files with size 0 into files with size 1 with content `\n`?

The point of this plugin is to help people think about this stuff *less*, because it doesn't matter.  So whenever a step invites this kind of thing, it's a smell.

I'm gonna close this as won't implement, but at the very worst, it's great to have this handy regex that you've built, so thanks for the great issue!  If this is unsatisfying, feel free to debate further, or, here are two things I would definitely merge:

- a docs page with a list of handy regex rules to help people get started
- a comprehensive look at a reasonable solution for for `trimTrailing` / `alwaysEndWithEmpty` / `removeConsecutive` that helps people think about this *less* rather than more
