### ISSUE TITLE
The header is updated with the new year although $YEAR is used in the template

### ISSUE THREAD

**Issue by jeanpierrefortune** [diffplug/spotless#337]
Hi,

We are facing an issue since the begining of the year.

All the file headers in the project are updated when spotlessApply is executed.

Environment:
```
Gradle 4.10.2
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Windows 10 10.0 amd64

```
Spotless configuration block:

```
spotless {
    java {
        target 'java/**/*.java'
        licenseHeaderFile '.build/spotless.license.txt'
        importOrder 'java', 'javax', 'org', 'com', 'com.diffplug', ''
        removeUnusedImports()
        eclipse().configFile '.build/spotless.eclipseformat.xml'
    }

    format 'misc', {
        target 'java/**/*.java', 'java/**/*.gradle', 'java/**/*.yml', 'java/**/*.md'
        indentWithSpaces()
        endWithNewline()
    }
}
```

Public repos:
https://github.com/calypsonet/keyple-java

Thanks for your help!

**Comment by jeanpierrefortune** [comment]
Hi,
I finally discovered why the date was changing!
The license file we use has different line breaks than those in the source file headers: 
- https://github.com/calypsonet/keyple-java/blob/develop/.build/spotless.license.txt
- https://github.com/calypsonet/keyple-java/blob/develop/java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/SendableInSession.java

That being said, I don't understand why this difference in headers wasn't detected earlier by spotless and it was the year change that revealed the problem.

**Comment by nedtwigg** [comment]
This diagnosis surprises me.  Are you sure that's the problem?  If you change the headers in the license file, does that help?  Spotless normalizes all of its inputs to `\n`, so I don't think the line endings you're pointing at should matter...

https://github.com/diffplug/spotless/blob/3c1741b04a3c4f77a54b38b2756655ff58fbde7d/lib/src/main/java/com/diffplug/spotless/generic/LicenseHeaderStep.java#L104

**Comment by nedtwigg** [comment]
Ahhhh, fascinating!  By line breaks you don't mean `\n`, you means the line lengths of the various paragraphs.

```gradle
    java {
        licenseHeaderFile '.build/spotless.license.txt'
        ...
        eclipse().configFile '.build/spotless.eclipseformat.xml'
    }
```

This means that first the license header is fixed, then the eclipse formatter fixes any violations the license header might have caused.  If you swapped the order, then you can have a license header that breaks the rules of the eclipse formatter.

Because the eclipse formatter is changing the format of the license header  `matchesLicenseWithYearToken` always returns false.

https://github.com/diffplug/spotless/blob/3c1741b04a3c4f77a54b38b2756655ff58fbde7d/lib/src/main/java/com/diffplug/spotless/generic/LicenseHeaderStep.java#L132-L137

Spotless is able to compose multiple steps because they are all just `Function<String, String>`.  Here are possible solutions to provide a warning to users for this unexpected behavior, simplest (but most work for user) to most complex:

1) If anyone else has this problem, they'll find this in the issue search.
2) Warn when license isn't the last step iff it's doing the year replacement thing
    + Something like `String FormatterStep::warningMessage(Formatter constructed)` which gets called when a Formatter is built, so the step can validate its index.  Some steps might "fight" to be first or last...
3) Provide a way for formatter steps to query the constructed formatter to provide warning messages to the user about system-wide misconfigurations
    + Something like `String FormatterStep::warningMessage(Formatter constructed, String exampleInput)` which would get called for the first file that gets formatted.  It's an opportunity for a step to feed itself into the full formatter and warn if it's getting obliterated.

I'm opting for `1` for now, but this will be useful example for the future if we find more reasons to build `2` or `3`.

**Comment by nedtwigg** [comment]
If you care about license headers, you should checkout [`ratchetFrom 'origin/master'`](https://github.com/diffplug/spotless/tree/master/plugin-gradle#ratchet).
