### ISSUE TITLE
Unreasonably large configuration performance overhead

### ISSUE THREAD

**Issue by oehme** [diffplug/spotless#348]
This line iterates the whole file collection, no matter if the task will execute or not. This is a large performance overhead, paid on every build invocation, no matter if spotless will be used or not. It should instead only check wether the collection itself is null. 

https://github.com/diffplug/spotless/blob/b38ee5a7b9f47bfe6a38749a19d09a751044b6eb/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L135

**Comment by nedtwigg** [comment]
I think that line is using this static import:

https://github.com/diffplug/spotless/blob/b38ee5a7b9f47bfe6a38749a19d09a751044b6eb/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L18

Which then calls this:

https://github.com/diffplug/spotless/blob/b38ee5a7b9f47bfe6a38749a19d09a751044b6eb/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/PluginGradlePreconditions.java#L24-L31

not this:

https://github.com/diffplug/spotless/blob/b38ee5a7b9f47bfe6a38749a19d09a751044b6eb/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/PluginGradlePreconditions.java#L33-L39

because target is an `Object[]`, but I might be making a mistake.  So I think it's only iterating over (N filecollections), not (file collection of size N).

**Comment by oehme** [comment]
It's not, I wouldn't have opened this issue if I hadn't seen it iterating the collection.

**Comment by oehme** [comment]
Sorry, I had linked the wrong line. Here is the real culprit: https://github.com/diffplug/spotless/blob/249d3caf58d31314857e15dfb14dd178a3060b4f/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessTask.java#L118

**Comment by nedtwigg** [comment]
Aha!  Thanks very much for the bug find 👍

**Comment by jbduncan** [comment]
Oh, oops! The use of `requireElementsNonNull` was my doing, so thank you @oehme for submitting the bug report, and thank you very much @nedtwigg for rectifying it for me!

**Comment by nedtwigg** [comment]
Published in 3.18.0
