### ISSUE TITLE
Make newline configurable

### ISSUE THREAD

**Issue by kec2** [diffplug/spotless#35]
Could newline please be configurable as not everybody uses unix newlines?

**Comment by nedtwigg** [comment]
Newline is configurable as documented in

- [README.md](https://github.com/diffplug/spotless/blob/9aefb65262685a9959360470b070e2e649f038eb/README.md#custom-rules)
- [javadoc](https://diffplug.github.io/spotless/javadoc/2.2.0/com/diffplug/gradle/spotless/SpotlessExtension.html#setLineEndings-com.diffplug.gradle.spotless.LineEnding-)

```
spotless {
    ...
    lineEndings 'GIT_ATTRIBUTES'    // can also be WINDOWS, UNIX, or PLATFORM_NATIVE
}
```

However, if you're using git, I would highly recommend keeping Spotless' default behavior which is to use git's line ending behaviors, and use `.gitattributes` to set the line endings to Windows.  Otherwise Spotless and Git will be fighting each other.

Here's more information on:
- [why it's important to sync your line endings with git](https://github.com/junit-team/junit5/issues/404#issuecomment-240248807)
- [how git determines line endings](https://github.com/diffplug/spotless/blob/master/CHANGES.md#version-200---august-16th-2016-javadoc-jcenter)
