### ISSUE TITLE
Built-in support for `.gitignore` patterns?

### ISSUE THREAD

**Issue by achaphiv** [diffplug/spotless#365]
I have a repository with `node_modules/` and other unrelated directories.

So this:

```
spotless {
  java {
    target '**/*.java'
```

takes a long time.

I was able to speed it up by using this naive approach:

```
spotless {
  def gitignorePatterns = file('.gitignore')
    .readLines()
    .findAll({ !it.startsWith('#') && !it.isEmpty() })
    .collect({ '**/' + it })

  java {
    target fileTree(rootDir) {
      include('**/*.java')
      exclude(gitignorePatterns)
    }
```

But that doesn't handle negated patterns.

So it would be nice to have proper support.

**Comment by jbduncan** [comment]
Hi @achaphiv, welcome to Spotless. :)

Interesting approach! Have you considered narrowing down the `include` to `src/**/*.java` or equivalent? Does that improve the speed of Spotless for you? 🤔

**Comment by achaphiv** [comment]
It does, but my project is actually composed of multiple subprojects. So the pattern is more like `**/src/**/*.java`.

Even then, it still ends up including ignored files.

E.G.
I have a [Serverless](https://serverless.com/) subproject which happens to have these file paths:

```
subproject-a/node_modules/serverless/lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/Context.java
subproject-a/node_modules/serverless/lib/plugins/aws/invokeLocal/java/src/main/java/com/serverless/InvokeBridge.java
```

I also did not mention the extra configuration I had for non-java files with less predictable file paths:

```
spotless {
  format 'misc', {
    target fileTree(rootDir) {
      include(
        '**/.dockerignore',
        '**/.editorconfig',
        '**/.gitignore',
        '**/Dockerfile',
        '**/lombok.config',
        '**/*.cls',
        '**/*.json*',
        '**/*.gradle',
        '**/*.md',
        '**/*.trigger',
        '**/*.xml',
        '**/*.yml'
      )
      exclude(gitignorePatterns)
    }

    indentWithSpaces(2)
    trimTrailingWhitespace()
    endWithNewline()
  }
``

**Comment by nedtwigg** [comment]
> It does, but my project is actually composed of multiple subprojects. So the pattern is more like `**/src/**/*.java`

In that case, I'd recommend applying spotless to each project separately.  Being more specific about your includes is definitely the easiest way to gain performance for this usecase.

Regardless, your broader point of reading `.gitignore` is reasonable, but there's a subtle problem with it which is important to note.

Spotless already respects `.gitattributes` for line-endings.  A `.gitattributes` file can be in any subdirectory, so the process goes like this:

- find every file specified in target (slog through all `**/*.ext`)
- search every subdirectory of those files for `.gitattributes`

If you wanted to fully support `.gitignore`, you would have the exact same problem.  This means that matching git's `.gitignore` behavior exactly won't be a speed improvement.  It might be a little of a speed improvement if you looked for `.gitignore` as you evaluate the globs in `target`, but I don't think you can do this without reimplementing gradle's glob implementation yourself.  There's no way that Spotless should take on the burden of maintaining a glob evaluator alongside gradle, and gradle probably doesn't want a PR for adding the necessary hooks so that you can reuse theirs.

You *could* do a speed improvement if you make the user say "here are the .gitignore files I care about", ala `gitignore('.gitignore', 'subdirA/.gitignore')`.  The thing is, if you're making the user do this manual work, you might as well just specify your target more precisely in the first place.  Such an approach will still be slower than specifying `target` more precisely, and it will be much more work to do the PR than to specify the target.  However, we'd be happy to merge it.

**Comment by nedtwigg** [comment]
Closing as almost-definitely-wontimplement.  Great discussion though, very glad this will pop in people's searches in the future.  Happy to reopen if anyone has more to say.
