### ISSUE TITLE
spotless-lib-extra 1.23.0 not on maven central

### ISSUE THREAD

**Issue by Kadrei** [diffplug/spotless#395]
We are using the `spotless-plugin-gradle` in version `3.+` but atm it is failing while resolving version `3.23.0` which depends on `com.diffplug.spotless:spotless-lib-extra:1.23.0`.

`com.diffplug.spotless:spotless-lib-extra:1.23.0` is not yet available on maven central: http://repo1.maven.org/maven2/com/diffplug/spotless/spotless-lib-extra/

Related Issue:
https://github.com/diffplug/spotless/issues/374

As this is the second time this problem arises we will most likely pin the minor version.

**Comment by uweschaefer** [comment]
same problem here

**Comment by nedtwigg** [comment]
Thanks for the headsup!  Our automatic deploys have been clobbered by https://github.com/bintray/gradle-bintray-plugin/issues/240

Best repeatability is automatic, but since that has now broken twice in a row without a clear workaround, we'll make a manual checklist to follow for future releases.

It is already available in jcenter, but mavenCentral is jammed, might take some doing to fix

**Comment by nedtwigg** [comment]
mavenCentral is unjammed, fixed now.
