### ISSUE TITLE
Feature Request: Prettier for maven

### ISSUE THREAD

**Issue by uweschaefer** [diffplug/spotless#435]
i noticed that npm.PrettierFormatterStep and npm.TsFmtFormatterStep are not supported from maven. Is there some technical reason for that, or was it just not needed by now?

**Comment by nedtwigg** [comment]
No technical reason.  Everything in Spotless is there because someone added a feature that they needed for themselves.  Happy to take a PR to add this.

Many projects get harder to work on as they get bigger.  One of the things we do to keep Spotless easy to work on is that we don't require contributors to "fill the matrix".  If you want to [add Bazel support](https://github.com/diffplug/spotless/issues/76), we'd happily accept the PR even if it only supported one formatter.  And if you want to add FooFormatter support, we'll happily accept the PR even if it only supports one build system.

Once someone has filled in one square of the formatter/build system matrix, it's easy for interested parties to fill in any empty squares, since you'll now have a working example for every piece needed.

**Comment by uweschaefer** [comment]
i see. i'll try to provide a PR, then. Thanks!

**Comment by nedtwigg** [comment]
Closed by #55, available in maven-plugin since `1.30.0`
