### ISSUE TITLE
Spotless ignore not enabled formatter sections

### ISSUE THREAD

**Issue by atrujillofalcon** [diffplug/spotless#446]
- [Gradle ] gradle or maven version
- [3.24.1] spotless version
- [Linux Manjaro ] operating system and version

In my team we like builders and Fluent API's keep in several lines. Apparently, Google Java Format inline these lines, but we use to apply  comments to don't format that specific lines. For example:

        // @formatter:on
        throw Problem.builder()
                .withStatus(Status.NOT_IMPLEMENTED)
                .build();
        // @formatter:on

If we apply Intellij Google Java Format plugin, ignore this line (the expected behavior), but Spotless Gradle plugin ignore this comments. Result:

        // @formatter:on
        throw Problem.builder().withStatus(Status.NOT_IMPLEMENTED).build();
        // @formatter:on

How we can configure to ignore this sections?

**Comment by jbduncan** [comment]
As an avid google-java-format user myself, I can confirm that google-java-format indeed doesn't support the `@formatter:(off|on)` tags.

@nedtwigg's workaround looks very sensible to me, so that's what I'd recommend if you want to use those tags.

As for the IntelliJ google-java-format plugin, I suspect the reason why it recognises the tags is because it partially delegates to IntelliJ's default formatter, which recognises the tags by default. But I don't have a computer with IntelliJ in front of me, so I'd have to confirm that some other time.

I hope our responses have answered your question, and if you still need help, please feel free to follow up. :)

**Comment by atrujillofalcon** [comment]
Thanks everybody, I'm going to apply the @nedtwigg suggestion that seems powerful and pretty customizable.

**Comment by atrujillofalcon** [comment]
@nedtwigg sorry for my english :)

**Comment by nedtwigg** [comment]
Just an update that since `plugin-gradle 5.5.0` and `plugin-maven 2.3.0`, it is now possible to use google-java-format [with `spotless:off` tags](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson).
