### ISSUE TITLE
Resource leak for maven plugin used with java eclipse formatter

### ISSUE THREAD

**Issue by pzygielo** [diffplug/spotless#447]
Resource leak for maven plugin used with java eclipse formatter

---
After `check` goal of `spotless maven plugin` ([1.24.1](https://github.com/diffplug/spotless/releases/tag/maven%2F1.24.1)) configured to use `java` > `eclipse`, temporary directory is left in filesystem.

Seems that below `deleteOnExit`
https://github.com/diffplug/spotless/blob/6c7db83068bd9bf92f6570b3f0845cbaf25aef5d/_ext/eclipse-base/src/main/java/com/diffplug/spotless/extra/eclipse/base/service/TemporaryLocation.java#L43-L50
is not enough, as directory is non-empty (contains subdirectory `org.eclipse.core.runtime`), and as such is not deleted on JVM exit.

**Comment by fvgh** [comment]
@pzygielo  
Thank's for the report.
I noticed the problem just recently while implementing #292. I am sure that for the initial versions of the Eclipse formatters the directory was always empty. That's why I never provided a better implementation. Now it seems to be used for file locks. Anyhow, for #292 I need some temporary files and maybe an extension of the implementation. But I also would like to have a look why the `.manager\.fileTableLock` is created in the first place. It is possible that I can improve some things in the setup of the Eclipse framework.

**Comment by pzygielo** [comment]
@fvgh - now that you brought hidden files to light (I missed them) - in top temporary dir `com_diffplug_spotless_extra_eclipse#...` there is also non-empty-with-files `.metadata` (but I'm sure you already know, or would know on the course of developing change).

**Comment by nedtwigg** [comment]
Fixed in `3.24.3`

**Comment by pzygielo** [comment]
> Fixed in `3.24.3`

As I am maven-ing, I upgraded plugin to **_1_**.24.3 (both tags happily refer to the same 0d08d584f :smile: anyway), and I confirm - no temporary files left after goal run.
Thank you.
