### ISSUE TITLE
control ktlint defect reporting format

### ISSUE THREAD

**Issue by nkiesel** [diffplug/spotless#493]
Hi,

ktlint default reporting format is plain which essentially emits a single line per defect while spotless shows the proposed patch instead.  Can spotless be customized to only show a single line?  In case it matters: we would be using the Gradle plugin for spotless.

**Comment by nedtwigg** [comment]
It sounds like you want a linter, rather than a formatter?  Spotless is a bad linter (although it does some on accident), but a great formatter.  From  [README](https://github.com/diffplug/spotless/blob/master/README.md):

> Ideally, a code formatter can do more than just find formatting errors - it should fix them as well. Such a formatter is really just a Function<String, String>, which returns a formatted version of its potentially unformatted input.

> It's easy to build such a function, but there are some gotchas and lots of integration work (newlines, character encodings, idempotency, and build-system integration). Spotless tackles those for you so you can focus on just a simple Function<String, String> which can compose with any of the other formatters and build tools in Spotless' arsenal.

The following links might help solve your problem:

- https://github.com/diffplug/spotless/blob/master/CONTRIBUTING.md#how-spotless-works
- https://github.com/diffplug/spotless/blob/master/lib/src/main/java/com/diffplug/spotless/kotlin/KtLintStep.java
