### ISSUE TITLE
Duplicate `clean` task

### ISSUE THREAD

**Issue by AllanWang** [diffplug/spotless#521]
As of spotless `3.27.0`, it seems like a `clean` task is created. I'm not sure about now, but at least a year ago, all new projects had a `clean` task created by the IDE by default:

```gradle
task clean(type: Delete) {
    delete rootProject.buildDir
}
```

The fix for us is to remove the inline `clean` task.

If this is expected, consider adding this in the [changelog](https://github.com/diffplug/spotless/blob/master/plugin-gradle/CHANGES.md). If this is not expected, can we avoid the naming conflict somehow?

**Comment by nedtwigg** [comment]
This is where we "create" the `clean` task:

https://github.com/diffplug/spotless/blob/c007dbac060d5dd413b252a6fcf98ab2784f71de/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPlugin.java#L31-L38

I think the way we're doing it now is the conventional way which plays nice with other plugins.  I think it would look like this for your example

```gradle
apply plugin: BasePlugin
tasks.getByName(BasePlugin.CLEAN_TASK_NAME).doLast {
    delete rootProject.buildDir
}
```

**Comment by AllanWang** [comment]
Can this be better documented? I'm fine with it, but it basically creates an error for any project that kept the default template until a change is made

**Comment by nedtwigg** [comment]
A quick git blame [shows](https://github.com/diffplug/spotless/blame/c007dbac060d5dd413b252a6fcf98ab2784f71de/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessPlugin.java#L32) that the line I linked to above is at least 2 years old, and it looks like `BasePlugin` has worked this way since [Gradle 2.0](https://docs.gradle.org/2.0/javadoc/org/gradle/api/plugins/BasePlugin.html).  In my faulty memory, this is the way that I've always created or hooked the clean task in plugins and buildscripts, so I don't remember a change, and I try to be thorough in the changelog.  I'm happy to merge a PR which updates the documentation or changelog to help others in your situation.  Having this issue in the search will be helpful to others who have that same IDE template too, so you've already provided a service to the project even if you don't have time for a PR :)

**Comment by nedtwigg** [comment]
Happy to reopen if there's further action or discussion to be had.
