### ISSUE TITLE
Indentation base for `googleJavaFormat()` is incorrect.

### ISSUE THREAD

**Issue by noel-yap** [diffplug/spotless#647]
The following code:

```
Array.of(
    …);
```

is correctly formatted under the Google Java Style Guide but `spotless` is reformatting it as:

```
Array.of(
        …);
```

**Comment by nedtwigg** [comment]
Spotless just calls out to `google-java-format`, using [version `1.7` by default](https://github.com/diffplug/spotless/blob/148ccd2f8f3f237c4ccfc3cc6032e7943453a805/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L35).  It's possible it has been fixed in the latest release `1.8`, which you can use with `googleJavaFormat('1.8')`, but it requires your build to run on JDK 11+.

If this is a bug, I believe it is a bug in google-java-format, not spotless.  If you want to workaround it within Spotless. you might be able to find a regex or [create a custom step](https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#custom-steps) to resolve it.
