### ISSUE TITLE
Bug in RemoveUnusedImportsStep (Windows only?)

### ISSUE THREAD

**Issue by jbduncan** [diffplug/spotless#65]
It seems that despite [this workaround](https://github.com/diffplug/spotless/commit/50cb15a102cf544ac043b9b1ead8613b4b797b98), the Windows related bug in google-java-format's removeUnusedImports method is still able to negatively affect Spotless, as demonstrated when one tries running `./gradlew test` against a75639f8bb637bd2caa221d18ae5d1e502b0da72, 601cff2d4987650f81aa2b7bd53c26bdd35fade3 and 8019dfe94d486bc856bbd1dfe06da7eb018aa2d0 on a Windows machine.

**Comment by jbduncan** [comment]
@nedtwigg Would this bug be worth raising over at https://github.com/google/google-java-format? As far as you can tell, is it something that affects all users of google-java-format or just Spotless?

**Comment by nedtwigg** [comment]
No clue, but I don't have time or interest to investigate this deeper.

**Comment by jbduncan** [comment]
I've sent a bug report to the google-java-format team: https://github.com/google/google-java-format/issues/112.

**Comment by jbduncan** [comment]
@nedtwigg I think this issue should be left open until https://github.com/google/google-java-format/issues/112 is resolved.

**Comment by nedtwigg** [comment]
Feel free to reopen!  You've got plenty enough commits to override me if you plan to take further action in the future :)

IMO, a bug tracker is only as good as the work it directs.  So if a bug is resolved enough that I'm not going to take any further action, I justify it as such and close it, since I'm not going to direct further action in that direction, and it can always be reopened.

This issue is already resolved for Spotless users except for the rare case (exhibited in junit) that there is a single-line comment between the license and the import.  In such a case, users have lots of ways to work around the issue.

Spotless is aggregating a lot of third-party libs.  My personal goal isn't to get them all to zero bugs - just to pad them enough to make them usable for most cases.  My quality bar has been met here, but if yours is higher, more power to you!!  Feel free to open however many bugs you would like :)

**Comment by jbduncan** [comment]
Ah, I see! Thank you for your thoughtful and insightful answer, I better understand now why you closed it in the first place, and I feel more confident in re-opening it myself now. :)

FYI I'm re-opening it as I intend to amend `GoogleJavaFormatStep#fixWindowsBug` in the near-ish future to run only when the google-java-format version is set to 1.1, as the bug has already been fixed in master and thus won't be around in 1.2.

**Comment by nedtwigg** [comment]
Looks like [1.2 has been released](https://github.com/google/google-java-format/releases/tag/google-java-format-1.2)!

Sees like this coupled with Kotlin and Scala support will make a nice 3.1 release.  Think you'll have time to look at this this week @jbduncan?

**Comment by jbduncan** [comment]
@nedtwigg Yep! I'm actually working on it ATM, so I hope to have something to share by the end of today.

**Comment by jbduncan** [comment]
I've just uploaded an initial PR! (https://github.com/diffplug/spotless/pull/73)

**Comment by jbduncan** [comment]
Done in https://github.com/diffplug/spotless/pull/73!
