### ISSUE TITLE
Support Gradle running on Java 7

### ISSUE THREAD

**Issue by gaborbernat** [diffplug/spotless#7]
can we add support for this please?

**Comment by nedtwigg** [comment]
Just to be clear, spotless can already format Java 7 code, but it requires that gradle is being run by Java 8+.

To allow spotless to run on Java 7, the following steps would need to be taken:
- Remove the Durian dependency.  It's only used in a few places, this is an easy fix.
- Convert all lambdas to anonymous inner classes.  Your IDE can do this for you.
- Misc. mopping up.

Spotless has a lot of lambdas, so it will decrease readability a fair bit.  But if you can't use it, it doesn't matter if it's easy to read.  If you make the chang, I'll be happy to merge.

**Comment by nedtwigg** [comment]
Something else to consider: Eclipse Neon (coming out in June 2016) will [require Java 8](http://blog.vogella.com/2015/08/18/eclipse-neon-eclipse-4-6-will-require-a-java-8-runtime/).  So in 9 months, the latest formatter with the latest bugfixes is going to require Java 8 anyway.

If anyone pulls off the Java 8 -> 7 conversion, I'd still be happy to merge it and release a version that works with Java 7.  But I'll definitely be reverting those changes in a year to make sure we always have the latest and greatest formatter available.

**Comment by gaborbernat** [comment]
I see your point. In the meantime I think it would be beneficial to
have a version Java 7 conversion.

On 8/27/15, Ned Twigg <notifications@github.com> wrote:
> Something else to consider: Eclipse Neon (coming out in June 2016) will
> [require Java
> 8](http://blog.vogella.com/2015/08/18/eclipse-neon-eclipse-4-6-will-require-a-java-8-runtime/).
>  So in 9 months, the latest formatter with the latest bugfixes is going to
> require Java 8 anyway.
>
> If anyone pulls off the Java 8 -> 7 conversion, I'd still be happy to merge
> it and release a version that works with Java 7.  But I'll definitely be
> reverting those changes in a year to make sure we always have the latest and
> greatest formatter available.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/diffplug/spotless/issues/7#issuecomment-135563511


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by nedtwigg** [comment]
If you've got a Java 7 constraint, and it's easier for you to backport
Spotless to Java 7 than it is to upgrade your constraint to Java 8, go for
it!  I'll merge and release, and maintain it as Java 7 for the next 9
months until Eclipse Neon is available.



Ned Twigg
Lead Software Architect, DiffPlug LLC
949-264-3433
340 S Lemon Ave #3433, Walnut, CA 91789

**Comment by nedtwigg** [comment]
Don't forget that the [gradle java plugin](https://docs.gradle.org/current/userguide/java_plugin.html) has these properties: `sourceCompatibility`, `targetCompatibility`.  You can upgrade the Java that's running your Gradle without upgrading your actual project.

**Comment by nedtwigg** [comment]
I've uploaded a `java7` branch.  At the moment, it has just two commits:

[Set compiler version to 1.7 and added the missing java functional interfaces](https://github.com/diffplug/spotless/commit/5a8cd340ca4acc7dee28b618c9c03a208de8a1c3)
[Remove the durian dependency and copy-paste its contents into spotless](https://github.com/diffplug/spotless/commit/03a046cb4819250fbea512d237946144239ace37)

The nice thing about this approach is that if people make improvements to master, it will be very easy to merge these improvements into the `java7` branch.  In order to make this work, you'd have to go through and replace all the lambdas and method references with anonymous inner classes.

I'm not convinced that finishing this is easier than upgrading a constraint, but if long-term Java 7 support is important to you, feel free to continue from here.

**Comment by gaborbernat** [comment]
I feel like changing the lambdas to anonymous inner functions would diverge the two project just as much as the canonical java implementation. :(

**Comment by nedtwigg** [comment]
Changing the lambdas to anonymous inner functions doesn't change the imports, and it doesn't change the functions you must supply to build a new plugin.

**Comment by nedtwigg** [comment]
Just a thought.  If this Java 7 port happens successfully, we could follow a similar path to release a Java 6 version, if anyone has that requirement.  Java 7 limits us to Mars, and Java 6 limits us to Kepler, but Kepler's formatter is still pretty darn good.

By far the hardest part of this whole project is the Java 8 -> Java 7 lambda and method reference conversion, but if that is accomplished, adding 6 would be relatively easy.  If Java 7 is accomplished, I'll create a separate issue for Java 6 outlining the process, so that if anyone needs it they can follow the steps.

**Comment by jtnelson** [comment]
Is this still happening?

**Comment by nedtwigg** [comment]
There is a [PR by gabor bernat which builds and runs under Java 7](https://github.com/diffplug/spotless/pull/8).  If you check it out and build it, and I believe it will work.

I haven't merged it because there are a few places where it replaces pure functions (which are hard to use incorrectly) with new kinds of objects that have init() methods which have to be managed correctly and have the right method called at the right time.  I'm happy to maintain a java7 port, but I'm not going to maintain a java7 rewrite.

Moving forward would be fairly straight forward.  If you check out the `java7` branch, there is an incomplete port in the functional style.  You'd basically just have to replace the method references which don't compile with the work that gabor did in his PR.

So the pieces are all there.  But projects are adopting java 8 waaaay faster than they adopted 6 or 7, so I think you're better off spending the time figuring out how to upgrade your build server to Java 8 ;-)  Eclipse Neon comes out in two months, and it requires Java 8, so right off the bat a Java 7 port is going to be missing bugfixes that the Java 8 port can do.

**Comment by jtnelson** [comment]
Thanks for the update. You're right, might as well upgrade to Java 8 :)

Sent from my iPhone




On Tue, Apr 12, 2016 at 7:33 AM -0700, "Ned Twigg" <notifications@github.com> wrote:












There is a PR by gabor bernat which builds and runs under Java 7.  If you check it out and build it, and I believe it will work.



I haven't merged it because there are a few places where it replaces pure functions (which are hard to use incorrectly) with new kinds of objects that have init() methods which have to be managed correctly and have the right method called at the right time.  I'm happy to maintain a java7 port, but I'm not going to maintain a java7 rewrite.



Moving forward would be fairly straight forward.  If you check out the java7 branch, there is an incomplete port in the functional style.  You'd basically just have to replace the method references which don't compile with the work that gabor did in his PR.



So the pieces are all there.  But projects are adopting java 8 waaaay faster than they adopted 6 or 7, so I think you're better off spending the time figuring out how to upgrade your build server to Java 8 ;-)  Eclipse Neon comes out in two months, and it requires Java 8, so right off the bat a Java 7 port is going to be missing bugfixes that the Java 8 port can do.

**Comment by nedtwigg** [comment]
Just updated to Eclipse Neon, which requires Java 8 and has a bunch of bugfixes relative to previous versions.  Very hard to justify a Java 7 version at this point.
