### ISSUE TITLE
Support gradle-node-plugin for prettier

### ISSUE THREAD

**Issue by breucode** [diffplug/spotless#728]
It would be great, if spotless supported https://github.com/node-gradle/gradle-node-plugin to download npm for prettier.
This would make it optional to install npm.

**Comment by dweiss** [comment]
I second this wholeheartedly. It really helps to keep things consistent because you can reuse the same npm for multiple needs.

A workaround would be to allow a lazy setup (at execution time) of npm binary. Then the wiring to gradle-node-plugin can be done manually. I've tried a custom npm-setup task and made spotlessInternalRegisterDependencies depend on it but I have no idea how configuration of spotless steps could be altered at execution time (I don't think I can set the npm path then, can I?).

**Comment by nedtwigg** [comment]
> I don't think I can set the npm path then, can I?

You can set the npm path ([docs](https://github.com/diffplug/spotless/tree/main/plugin-gradle#npm-detection), [code](https://github.com/diffplug/spotless/blob/75fdd3ece5857687a05d0259df66f4de4661dabc/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L501-L512)). I *think* it has to be set at configuration-time, not execution time.

Happy to take a PR to improve this situation.

**Comment by dweiss** [comment]
Sorry, I wasn't clear - I know npm path can be set at configuration time. I don't think it can be set afterward, at execution time. This is the difference that would make it possible to run with gradle-node-plugin because then you wire up a dependency between spotless and gradle-node-plugin's npminstall, add a doFirst clause to spotless task and set up the npm path pointing at the right location.

My experiment shows this is currently impossible because npm path resolution takes place eagerly at configuration time.

**Comment by nedtwigg** [comment]
`doFirst` runs *after* `@TaskAction`, which is surprising. It's only "first" compared to `doLast` actions, unfortunately.  But agreed, there would be more flexibility if you could set the exe at execution time, and I'm happy to merge a PR that does that.

FYI, I use this [tiny little buildsrc plugin](https://github.com/mytakedotorg/mtdo/blob/staging/buildSrc/src/main/java/org/mytake/gradle/node/NodePlugin.java) which lazily installs node at configuration time, to workaround this and other similar issues.

**Comment by dweiss** [comment]
Really? Well, even if then you could just add a task dependency in between to set the exe path - you get the gist. I didn't think about using buildsrc to set up node beforehand, good tip. May look into this, eventually. I'd love to provide a patch but I'm swamped in work already, eh.

**Comment by rnorth** [comment]
Thank you for the great plugin - it's really useful!

Just to share, we're facing this same challenge and have a working setup - but some minor caveats.

This works for us:
```
plugins {
    ...
    id 'com.diffplug.spotless' version '5.14.2'
    id "com.github.node-gradle.node" version "2.2.4"
}

spotless {
    java {
        prettier(...)
                .npmExecutable("$node.variant.npmExec")
                .config(...)
    }
}

spotlessInternalRegisterDependencies.dependsOn(nodeSetup)
```

The caveats are:

* `spotlessInternalRegisterDependencies.dependsOn(nodeSetup)` seems to be the only reliable way to make all potential spotless invocations work. The `Internal` in the name makes this uncomfortable, so I'd be keen to know if there's a better way to specify this task dependency. 
* (Not relevant to spotless, but maybe of interest) `node-gradle` [recently removed the property which exposes the path to npm](https://github.com/node-gradle/gradle-node-plugin/issues/55#issuecomment-782200463), so we're locked to a specific version of that plugin at present.

**Comment by nedtwigg** [comment]
Thanks to a series of great PRs from @simschla, this is now possible in `plugin-gradle 6.14.0`. See [this](https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/test/resources/com/diffplug/gradle/spotless/NpmTestsWithoutNpmInstallationTest_gradle_node_plugin_example_1.gradle) or [this](https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/test/resources/com/diffplug/gradle/spotless/NpmTestsWithoutNpmInstallationTest_gradle_node_plugin_example_2.gradle) example.
