### ISSUE TITLE
Consider bumping default version of google-java-format from 1.1 to 1.2.

### ISSUE THREAD

**Issue by jbduncan** [diffplug/spotless#74]
I think this is a worthwhile change to pursue, but before opening a PR, I want to understand the pros and cons of it.

These are the pros and cons I can think of at the moment:

**Pros:**
- More "correct" behaviour by default.

**Cons:**
- Can break people's builds if they depend on the default version being 1.1.
- Requires a new version of `spotless-lib` (but that would be par for the course).

**Comment by nedtwigg** [comment]
For the most part, I expect `spotless-lib` and `spotless-plugin-xxx` are going to release in lockstep.  `lib` gets an upgrade, so we release a new set of `spotless-plugin-xxx` which point to that upgrade.

As far as newer formatters breaking older formatters, I think spotless defaults should always use the latest version of all available formatters.  Users don't have to upgrade to new Spotless versions (I've got old projects sitting around on 1.x because they rely the old version of the eclipse formatter).  And thanks to our classpath isolation introduced in Spotless 3.x, if they upgrade Spotless and are not happy with the new version of a dependendent library, they can always set the version of that library after the fact.

**Comment by jbduncan** [comment]
Hi @nedtwigg, thanks for writing up your opinion on this!

Done in https://github.com/diffplug/spotless/pull/73. :)
