### ISSUE TITLE
Don't mangle complex enums

### ISSUE THREAD

**Issue by galen-pivotal** [diffplug/spotless#77]
I'm working on [Apache Geode](https://github.com/apache/geode), and I'm noticing enums getting mangled by Spotless. As far as I can tell, there is no setting for Spotless to make it handle complex enum types in the way that most of us would format them by hand. It looks like what's happening is just that the parser views this as a run-on statement and just keeps line breaking and indenting further.

For example:
```
public static enum Command {
    START("start", "bind-address", "hostname-for-clients", "port", "force", "debug",
        "help"), STATUS("status", "bind-address", "port", "member", "pid", "dir", "debug",
            "help"), STOP("stop", "member", "pid", "dir", "debug",
                "help"), VERSION("version"), UNSPECIFIED("unspecified");
[...]
}
```

I would much rather write this as:

```
public static enum Command {
    START("start", "bind-address", "hostname-for-clients", "port", "force", "debug", "help"),
    STATUS("status", "bind-address", "port", "member", "pid", "dir", "debug", "help"),
    STOP("stop", "member", "pid", "dir", "debug", "help"),
    VERSION("version"),
    UNSPECIFIED("unspecified");
[...]
}
```
All these enum variants are smaller than the line width, so that's not an issue here.

I would love to at least have an option to make enums format the second way. It looks like a bug to me for them to format the first way.

**Comment by jbduncan** [comment]
Hi @galen-pivotal, would you be at liberty to share the Spotless configuration in your Gradle build script with us?

It's not terribly clear to me from your description if this happening because of a bug in Spotless, or one of the formatters it uses (like the Eclipse Java formatter), or a bug in your config.

**Comment by jbduncan** [comment]
And could you also share with us which version of Spotless you're using?

**Comment by jaredjstewart** [comment]
Here is our gradle build script: https://github.com/apache/geode/blob/develop/build.gradle
It points to an eclipse formatter file from the Google style guide: https://github.com/apache/geode/blob/develop/etc/eclipse-java-google-style.xml

We're using version `com.diffplug.gradle.spotless:spotless:2.2.0`.

**Comment by jbduncan** [comment]
Hi @galen-pivotal and @jaredjstewart.

I can only think that it's a problem with [eclipse-java-google-style.xml](https://github.com/apache/geode/blob/develop/etc/eclipse-java-google-style.xml), because when I run `spotlessApply` against `geode\develop` with the contents of [eclipse-java-google-style.xml](https://github.com/apache/geode/blob/develop/etc/eclipse-java-google-style.xml) replaced with [Junit 5's own eclipseformat.xml file](https://github.com/junit-team/junit5/blob/master/src/eclipse/junit-eclipse-formatter-settings.xml), the enum constants in [`LocatorLauncher.Command`](https://github.com/apache/geode/blob/develop/geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java#L1845) do line up nicely.

(It's not clear to me why, but when I replace the contents of eclipse-java-google-style.xml with Spotless's own [`spotless.eclipseformat.xml`](https://github.com/diffplug/spotless/blob/master/spotless.eclipseformat.xml), it produces the exact same enum-constant-misalignment problem. @nedtwigg, should an issue be raised for this?)

Just now I tried replacing the following lines in Geode's spotless config...
```gradle
classpath "com.diffplug.gradle.spotless:spotless:2.2.0"
. . .
eclipseFormatFile "${project(':geode-core').projectDir}/../etc/eclipse-java-google-style.xml"
```
with... 
```gradle
classpath "com.diffplug.spotless:spotless-plugin-gradle:3.0.0"
. . .
googleJavaFormat('1.2')
```

in the hope that it would allow you to follow the Google Java Style more closely, but that actually introduces an entirely different problem! (It throws an exception saying it cannot reorder imports in [`LoaderHelperImpl`](https://github.com/apache/geode/blob/develop/geode-core/src/main/java/org/apache/geode/internal/cache/LoaderHelperImpl.java) because there are comments in between the imports.)

My suggestion for now is to investigate how eclipse-java-google-style.xml and JUnit 5's eclipseformat.xml differ, find out which lines (or lack of lines) cause JUnit 5's eclipseformat.xml to work properly, and create your own custom `geode.eclipseformat.xml` with these lines added/removed.

@nedtwigg, do you have any thoughts on this?

**Comment by jbduncan** [comment]
As a side note, I've raised an [issue](https://github.com/google/google-java-format/issues/116) with google-java-format regarding the exception it throws when `googleJavaFormat(1.2)` is used instead of `eclipseFormatFile [...]`.

**Comment by nedtwigg** [comment]
Looks like there are some helpful tidbits here:

http://stackoverflow.com/questions/6676305/how-to-stop-eclipse-formatter-from-placing-all-enums-on-one-line

**Comment by jbduncan** [comment]
(To continue my earlier side-note, it seems that the exception thrown by google-java-format when it sees comments in-between imports is actually intended! So I've closed the [issue](https://github.com/google/google-java-format/issues/116) on google-java-format for now.)

**Comment by galen-pivotal** [comment]
Ah, it does look like this is an issue with the Google style guide, or at least changing the value of `org.eclipse.jdt.core.formatter.alignment_for_enum_constants` from `0` to `48` causes enums to be lined up.

I'd ideally like to allow either formatting of all enum constants on one line (if they don't have arguments) or split per line. I haven't checked, but I suspect the Eclipse formatter won't do anything that complicated. Regardless, it looks like Spotless actually calls out to Eclipse's formatter (via the Gradle plugin), so they're the one I'd want to file a feature request with.

Thanks for being so helpful and informative!

**Comment by jbduncan** [comment]
You're very welcome @galen-pivotal. :)

I realise now that I should have explicitly pointed out that Spotless forwards onto the official Eclipse formatter whenever a user calls `eclipseFormatFile [...]`, so please accept my apologies.

I don't know if you're the right person to ask, but I wonder if I may hear the Geode team's reasons as to why they decided to use the Google Java Style guide's eclipseformat.xml rather than Spotless's support for google-java-format. Did they simply not know of google-java-format's existence, or was there a more technical reason that prevented its adoption?

**Comment by galen-pivotal** [comment]
@jbduncan I'm not sure the reasons; @jaredjstewart probably knows better than I. Perhaps I should have asked more of the Geode folks before filing an issue with you >.< I'll let you know if I find out!

**Comment by jaredjstewart** [comment]
I believe the initial thought was that by using an eclipse format file we would only have two formatters (eclipse xml, intellij xml) to keep in sync if we made modifications, rather than three (eclipse xml, intellij xml, google-java-format).
