### ISSUE TITLE
Javadoc AccessDenied error

### ISSUE THREAD

**Issue by yooksi** [diffplug/spotless#775]
Just a quick heads up that the link to Spotless [Javadoc](https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.7.0/com/diffplug/gradle/spotless/JavaExtension.html) is currently not working.

The origin of the hyperlink is from the [Java section](https://github.com/diffplug/spotless/tree/master/plugin-gradle#java) of `spotless/gradle-plugin` Readme.

**Comment by nedtwigg** [comment]
Thanks. I looked into this a while ago, and couldn't figure it out.

https://github.com/maxcellent/javadoc.io/issues/58

If anybody figures out why javadoc.io can't serve our javadoc anymore, let me know. Maybe our javadoc jars are broken somehow?

**Comment by nedtwigg** [comment]
Possibly useful: for gradle, `5.6.0` works, `5.7.0` and later does not

- https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.6.0/com/diffplug/gradle/spotless/FormatExtension.LicenseHeaderConfig.html
- https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.7.0/com/diffplug/gradle/spotless/FormatExtension.LicenseHeaderConfig.html

**Comment by nedtwigg** [comment]
Doh. The reason is that javadoc.jar in `5.6.0` is 207996 bytes, while `5.7.0` is only 261 bytes. The code and sources are being deployed correctly, but something is broken about how we ship javadoc. This is true for both plugin-gradle and lib, 

- https://repo1.maven.org/maven2/com/diffplug/spotless/spotless-plugin-gradle/5.6.0/
- https://repo1.maven.org/maven2/com/diffplug/spotless/spotless-plugin-gradle/5.7.0/

This was masked a bit because javadoc.io did also change its URL scheme around the same time. I'll take a whack at fixing this next week.
