### ISSUE TITLE
Can't setup ktfmt via gradle according to docs

### ISSUE THREAD

**Issue by ColtonIdle** [diffplug/spotless#858]
I have an android project.

In my root build.gradle.kts I added the spotless plugin to my plugin block

then

```
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        ktfmt("0.24").dropboxStyle()
    }
}
````

If I run ./gradlew build I get an error of 

```
* What went wrong:
Cannot add task 'clean' as a task with that name already exists.
```

Android projects by default come with this

```
tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}
```

so I removed that, and then I get a different error

```
* What went wrong:
A problem occurred configuring root project 'my-android-app'.
> Could not create task ':spotlessKotlinCheck'.
   > Could not create task ':spotlessKotlin'.
      > You must either specify 'target' manually or apply a kotlin plugin.
```

**Comment by jbduncan** [comment]
These are both behaviours of Spotless that I've seen before.

My understanding is Spotless wasn't fully coded with Android in mind, so as a workaround, try adjusting your `clean` like so:

```kotlin
tasks.named("clean", Delete::class) {
    delete(rootProject.buildDir)
}
```

...so that it refers to the `clean` task from the Java plugin, which Spotless imports indirectly.

And then, if it still reports that last error message, you'll need to tell Spotless where your Kotlin source files actually are with a "target". For example, if you have an `app` subproject, you can tell Spotless about it like so:

```kotlin
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("app/src/**/*.kt")
        ktfmt("0.24").dropboxStyle()
    }
}
```

I'm assuming that your `spotless` is in your root `build.gradle.kts`, if you have more than one. If the `spotless` block is actually in e.g. your `app/build.gradle.kts`, then the "app/" of the target would go away, if I understand correctly.

I hope this helps!

Having said all this, this does sound like a bug, so @nedtwigg do you have any other thoughts?

**Comment by jbduncan** [comment]
@ColtonIdle I should add that this is all going from memory, so if it doesn't work the way expected, please let us know!

**Comment by ColtonIdle** [comment]
@jbduncan AHHH It worked!

Thank you so much!

Quick questions if you don't mind.

1. The tip about how to change the clean task was great. Do you think it's worth filing a bug for Android Studio to generate tasks.named instead of tasks.register? Or is this more-so a bug on spotless' part?
2. Naming the targets was indeed my issue... but is there any way to just say "ALL .kt and .kts files?" I'll play around with this, but in general I'm curious if that's recommended or if that's shooting myself in the foot somehow.

**Comment by jbduncan** [comment]
Good questions!

1. It's a Spotless issue I reckon, because you only need to use `tasks.named` if `clean` exists already. The reason why it's there already because Spotless always imports it from Gradle's Base plugin.

Regardless, in most Android projects, `clean` comes out of the box as part of the root `build.gradle`, rather than with the Android plugin (for some reason). So raising a bug report about it might lead to the Android Devs saying "no", because if they fixed it then it would break most projects.

Feel free to raise a bug report about having `clean` be part of the Android plugin anyway, as it might encourage the devs to build `clean` into a future, breaking version of the plugin anyway, but I wouldn't count on it. :)

2. Yep, that target works! Just be warned that it may be slow. So try `app/src/**/*.kt` (assuming all your Kotlin files live under "app/src") to speed things up a bit.

**Comment by jbduncan** [comment]
I'm closing this as it looks like everything is resolved now. If not, please let us know and we'll reopen.

**Comment by jbduncan** [comment]
And of course I promptly forgot that I said this is likely a Spotless bug. Oops! Reopening.

**Comment by ColtonIdle** [comment]
@jbduncan thanks for the advice. Filed a bug here: https://issuetracker.google.com/issues/186924459

In regards to your advice of ` app/src/**/*.kt`... I use multiple modules in this project. Maybe about 30 modules and so it seemed like this was the simple way of defining that I want to format all of my modules kt files.

**Comment by nedtwigg** [comment]
#1014 fixes the conflict with the `clean` task.

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle/6.0.3`.

**Comment by ColtonIdle** [comment]
@nedtwigg after all these years... the android studio team (because of a bug I filed) is going to get rid of the clean task in the template.

https://issuetracker.google.com/issues/186924459

Just posting this as a heads up. I'm not sure if it backfires with that latest PR you made to address this.

**Comment by nedtwigg** [comment]
Thanks for the heads up! No backfire, Spotless is strictly more resilient now than it was before, so all good.
