### ISSUE TITLE
Could someone explain what caused this change?

### ISSUE THREAD

**Issue by al-tr** [diffplug/spotless#864]
This is not a bug report but a question about some ambiguous behavior, basically "what is the correct behavior in this case?"

There's a difference in format between 5.8.2 (and earlier) and 5.9.0 (and later including 5.12.2) explained here: https://github.com/al-tr/spotless-diff/pull/1/files
format.xml: https://github.com/al-tr/spotless-diff/blob/5.8.2/spotless.eclipseformat.xml
Though I don't see any obvious change that caused it: https://github.com/diffplug/spotless/compare/gradle/5.8.2...gradle/5.9.0

About format.xml: removing any of two rules results into 5.9.0 format be the same as 5.8.2, only this combination causes "insert new line after annotation on parameter"

eclipse formatter plugin in intellij idea formats code to the 5.8.2 version (can't confirm about the actual eclipse because I don't use it, sorry 😄)

**Comment by nedtwigg** [comment]
Probably because of this changelog entry:

- Bump `eclipse-jdt` default version from `4.17.0` to `4.18.0`

You can pin the eclipse JDT version by doing `eclipse('4.17.0')` and then you can get bugfixes and performance enhancements in new versions of Spotless without default versions changing underneath you.
