### ISSUE TITLE
Gradle 7 warning: Execution optimizations have been disabled ... ':spotlessFoo' uses this output of task ':spotlessBar'

### ISSUE THREAD

**Issue by yonatankarp** [diffplug/spotless#870]
After integrating the latest `spotless` (5.12.5) into my project with Gradle DSL Kotlin `7.0.1` whenever I'm running my build I have the following warning:
```shell
> Task :spotlessKotlinGradle
Execution optimizations have been disabled for task ':spotlessKotlinGradle' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '<MY_PROJECT>'. Reason: Task ':spotlessKotlinGradle' uses this output of task ':spotlessKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '<MY_PROJECT>/build/spotless/spotlessKotlinGradle'. Reason: Task ':spotlessKotlin' uses this output of task ':spotlessKotlinGradle' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

My Spotless configuration is as follow:
```kotlin
configure<SpotlessExtension> {
    kotlin {
        target(fileTree(".") {
            include("**/*.kt")
            exclude("**/.gradle/**", "**/openapi/**")
        })
        // see https://github.com/shyiko/ktlint#standard-rules
        ktlint("0.41.0").userData(
            mapOf(
                "no-unused-imports" to "true",
                "no-wildcard-imports" to "true",
                "import-ordering" to "true",
                "insert_final_newline" to "true",
                "string-template" to "true"
            )
        )
    }
    kotlinGradle {
        target(fileTree(".") {
            include("**/*.gradle.kts")
        })
        trimTrailingWhitespace()
        ktlint()
    }
}
```

**Comment by nedtwigg** [comment]
Your quote of the error message above includes `'...'. Reason:`. Can you supply the `...`, or does Gradle actually print `...`

**Comment by yonatankarp** [comment]
the `...` Is the path to my project - I've updated the log to reflect it better

**Comment by mrt181** [comment]
This is a deprecation warning from gradle 7.
I get this for a java project:

```
 > ./gradlew spotlessApply --warning-mode all
> Task :spotlessMisc
Execution optimizations have been disabled for task ':spotlessMisc' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/c/Users/r892107/repos/atf/atf-model/java/build/spotless/spotlessMisc'. Reason: Task ':spotlessJava' uses this output of task ':spotlessMisc' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: '/c/Users/r892107/repos/atf/atf-model/java/build/spotless/spotlessMisc'. Reason: Task ':spotlessJava' uses this output of task ':spotlessMisc' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.0.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 3s
4 actionable tasks: 4 executed
```

And the mentioned link: https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency

**Comment by nedtwigg** [comment]
Thanks for the examples, I think I know what's happening in both cases. The root problem is that our docs and examples used to have `**/*.blah`. That was bad advice, `prefix/**/*.blah` or `*.blah` are *much* better. Using `**/*.blah` *can* work, but it's easy to accidentally depend on the outputs of a different Spotless task, which is what's happening in the examples above.

For each Spotless format `foo`, there is a folder `build/spotless/spotlessFoo`. The `spotlessFoo` task writes the correctly formatted version of every file into that directory (or no file if the input is already correct).

So let's say I have this:

```gradle
spotless {
  java { ... }
  format 'misc', {
    target fileTree('.') { include '**/*' } ...
```

Then my project folder is gonna end up like this:

```java
src/main/Foo.java // source file
build/spotless/spotlessJava/src/main/Foo.java // spotless folder for java
build/spotless/spotlessMisc/src/main/Foo.java // spotless folder for misc
build/spotless/spotlessMisc/build/spotless/spotlessJava/src/main/Foo.java // Oops! spotlessMisc depends on spotlessJava
```

Notice in my example above that I passed `fileTree` explicitly. If instead I did this:

```gradle
spotless {
  java { ... }
  format 'misc', {
    target '**/*'
```

Then you won't see this problem, because we detect the `**/*` and automatically assume that you mean to exclude the `build`, `.git`, and `.gradle` directories:

https://github.com/diffplug/spotless/blob/0842bfa67ff0a6b289fc8a924a314d194e0d50d5/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L234-L246

But if you pass a `FileTree` then we can't tell if it's a `**/*` or not, since we aren't the ones who built it. Also, if you pass `targetExclude` explicitly, then you can override the excludes that we inferred. I think one of these two things (`fileTree` or `targetExclude`) is what's happening in all the cases above. I'm also not sure what more we can do to prevent this.

- Gradle tells you which Spotless task has an overly broad target
- Gradle also tells you which folder it is slurping, so you know how to change its `target` and/or `targetExclude`
- If you use the built-in `target 'string'`, then we actively detect `**/*` and try to prevent the obvious footguns.
- But there are people who want to do weird stuff (e.g. autogenerate code into `build`, and then use Spotless to format it), so I don't think we can fo much farther in terms of hardcoding exclusions.

@yonatankarp and @mrt181 please reopen if this doesn't solve your issue.
