### ISSUE TITLE
Inconsistent Continuation indent for googleJavaFormat 1.11.0

### ISSUE THREAD

**Issue by overfullstack** [diffplug/spotless#903]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
Observed inconsistent Continuation index for the same function call. In the screenshot attached, for the same function call `validateAndFailFast` the top call has 8 indentation and bottom one has 4.

![image](https://user-images.githubusercontent.com/13434911/127771456-a45856bf-41b9-4760-b877-874685d61f86.png)

- [x] gradle or maven version - Gradle - 7.1.1
- [x] spotless version - Using Gradle plugin - id("com.diffplug.spotless") version "5.14.2"
- [x] operating system and version - Mac OS X 11.5
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

```
spotless {
  kotlin {
    target("src/main/java/**/*.kt", "src/test/java/**/*.kt")
    targetExclude("$buildDir/generated/**/*.*")
    ktlint("0.41.0").userData(mapOf("indent_size" to "2", "continuation_indent_size" to "2"))
  }
  kotlinGradle {
    target("*.gradle.kts")
    ktlint("0.41.0").userData(mapOf("indent_size" to "2", "continuation_indent_size" to "2"))
  }
  java {
    target("src/main/java/**/*.java", "src/test/java/**/*.java")
    targetExclude("$buildDir/generated/**/*.*")
    importOrder()
    removeUnusedImports()
    googleJavaFormat("1.11.0")
    trimTrailingWhitespace()
    indentWithSpaces(2)
    endWithNewline()
  }
  format("xml") {
    targetExclude("pom.xml")
    target("*.xml")
    eclipseWtp(XML)
  }
  format("markdown") {
    target("*.md", "*.adoc")
    trimTrailingWhitespace()
    indentWithSpaces(2)
    endWithNewline()
  }
```

**Comment by jbduncan** [comment]
This is a known behaviour of google-java-format.

I personally like it, because it helps to distinguish the parameters of the first `validateAndFailFast` call from the `or` call straight after it. But I can see why you think it's inconsistent.

If you're not fond of this, there's only two things I can suggest, which I fear you're not going to like:

1. Raise an issue on github.com/google/google-java-format to see if they might introduce a flag to change this behaviour (but I wouldn't raise my hopes as GJF is pretty opinionated).
2. Use a different formatter like Eclipse or Prettier.

I'm going to close this because I believe there isn't anything we can do about this behaviour. But feel free to respond if you think otherwise.

**Comment by overfullstack** [comment]
@jbduncan Thanks! is there a way I can configure my .editorconfig to follow this rule? The current "ij_java_continuation_indent_size = 4" doesn't get me this as I do `cmd+shift+l`.

**Comment by jbduncan** [comment]
@overfullstack You're welcome!

Good question, I don't actually know. I'd be pleasantly surprised if there is such a rule in .editorconfig, as I seem to remember that part of the reason why GJF was created in the first place was because Eclipse and IntelliJ IDEA's formatters weren't flexible enough for Google's needs at the time, and this may still be the case. (Sorry, I was hoping to find a reference, but I can't find it right now.)

If you want your code to be formatted the GJF way in IntelliJ, then I suggest installing the [google-java-format plugin](https://plugins.jetbrains.com/plugin/8527-google-java-format). It's not perfect as it doesn't use the latest version of GJF and it doesn't format imports at all, but other than that, it allows you to replace the default formatter used by shortcut <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> with GJF on a per-project basis, and I find it works well. (But I'm biased; I prefer pressing <kbd>Ctrl</kbd>+<kbd>Ctrl</kbd> and entering `gradle spotlessApply` instead!)

I hope this helps.
