### ISSUE TITLE
Empty line at the end of *.kt file even if 'endWithNewline()' is not uncluded

### ISSUE THREAD

**Issue by aivanovski** [diffplug/spotless#908]
Spotless produces empty lines at the end of Kotlin files even if option `endWithNewline()` is not specified in config. Meanwhile option `endWithNewline()` works fine for *.java and *.xml files.

- Gradle 7.0, Android
- Spotles Gradle plugin: com.diffplug.spotless:spotless-plugin-gradle:5.14.2
- Spotless config:
```
    kotlin {
        target '**/*.kt'
        ktlint()
        trimTrailingWhitespace()
        indentWithSpaces()
    }
```

**Comment by jbduncan** [comment]
I could be wrong, but I suspect it's a behaviour of ktlint itself.

Have you tried running just ktlint itself as per their Gradle instructions on their [homepage](https://ktlint.github.io/), by any chance? If you get the blank lines still, then that indicates it's ktlint's fault, otherwise it's ours. :)

**Comment by aivanovski** [comment]
Exactly! There is an option in ktlint called `insert_final_newline` which is set to `true` by default.
This option can be turned off in a two ways: 1 - in ".editorconfig" file, 2 - in gradle configuration, by providing line to `ktlint()` option.

@jbduncan Thank you for advice.
