### ISSUE TITLE
kotlin's value class not parsed correctly

### ISSUE THREAD

**Issue by ikovalyov** [diffplug/spotless#912]
- Gradle 7.1.1
- Spotless "5.14.2"

```
package com.github.ikovalyov.model.security

import kotlin.jvm.JvmInline

@JvmInline value class Email(val value: ShortString)
```

```
> Task :spotlessKotlin FAILED
Step 'ktfmt' found problem in 'src/commonMain/kotlin/com.github.ikovalyov.model/security/Email.kt':
5:12: error: Expecting a top level declaration
com.facebook.ktfmt.ParseError: 5:12: error: Expecting a top level declaration

```

It works fine with inline class:
```
inline class Email(val value: ShortString)
```

**Comment by nedtwigg** [comment]
Might want to try setting `ktfmt('something.latestversion')`, it may already have been fixed since Spotless updated its default versions. Regardless, this is a bug to report at the [ktfmt repo](https://github.com/facebookincubator/ktfmt/tags), and as soon as they release a fix, you can use it in Spotless by specifying the fixed version.

**Comment by ikovalyov** [comment]
thanks
